management:
  server:
    port: 8080
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
#    git:
#      mode: full
  endpoint:
    health:
      show-components: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: hello-actuator
    company: dev.leonkim

logging:
  level:
    dev.leonkim.controller: debug
